# Generated by Django 5.2.16 on 2026-07-12 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payer_reference', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(db_index=True, default='Initiated', max_length=50)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkash_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BkashAgreements',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.bkashagreement'),
        ),
    ]
