# Generated by Django 5.2.16 on 2026-07-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bkashagreement_payment_bkash_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bkash_agreement',
        ),
        migrations.DeleteModel(
            name='BkashAgreement',
        ),
    ]
